version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_PASS: wise2c
      RABBITMQ_DEFAULT_USER: wise2c
    ports:
    - 5672:5672/tcp
    - 15672:15672/tcp
  consul-server:
    image: consul:0.7.0
    ports:
    - 8500:8500/tcp
    command:
    - agent
    - -server
    - -client=0.0.0.0
    - -dev
    - -node=node0
    - -bootstrap-expect=1
    - -data-dir=/tmp/consul
  artifactory:
    image: wisecity/artifactory-oss:5.2.0
    ports:
    - 18081:8081
  database:
    image: mysql:5.7
    ports:
    - 3306:3306
    environment:
      MYSQL_DATABASE: wise2c
      MYSQL_ROOT_PASSWORD: wise2c2017
    volumes:
    - /var/lib/cloud-data:/var/lib/mysql
    volumes_from:
    - mysql-server-datavolume
  mysql-server-datavolume:
    image: wisecity/mysql-sidekick
  wise2build-biz:
    image: registry.aliyuncs.com/wise2c-test/build-biz:stable
    ports:
    - 16060:16060
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    links:
    - database
    - consul-server
    - rabbitmq
    - artifactory
    - redis
    command:
    - --system.defaultRegistry=docker.io
    - --spring.datasource.url=jdbc:mysql://database:3306/builderdb?useUnicode=true&characterEncoding=utf-8
    - --spring.datasource.password=wise2c2017
    - --spring.datasource.username=root
    - --spring.cloud.consul.host=consul-server:8500
    - --spring.rabbitmq.addresses=rabbitmq:5672
    - --spring.rabbitmq.adminAddresses=http://rabbitmq:15672
    - --spring.rabbitmq.nodes=rabbit@rabbitmq
  wise2build-frontend:
    image: registry.aliyuncs.com/wise2c-dev/workflow-ui:stable
    environment:
      CONSUL: consul-server:8500
    links:
    - wise2build-biz:workflow
    - build-schedule:schedule
    - consul-server:consul-server
    - document:document
    ports:
    - 8081:80/tcp
    restart: always
  wise2build-worker:
    image: registry.aliyuncs.com/wise2c-test/build-worker:stable
    environment:
      WORKER_HOME: /data/worker
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /data/worker:/data/worker
    - /tmp:/tmp
    links:
    - consul-server
    - rabbitmq
    - artifactory
    ports:
    - 6061:6061/tcp
    command:
    - --worker.diskUsageLimit=85
    - --spring.cloud.consul.host=consul-server:8500
    - --spring.rabbitmq.addresses=rabbitmq:5672
    - --spring.rabbitmq.adminAddresses=http://rabbitmq:15672
    - --spring.rabbitmq.nodes=rabbit@rabbitmq
  document:
    image: nginx
  build-schedule:
    image: registry.aliyuncs.com/wise2c-dev/build-schedule:stable
    ports:
    - 9595:9595
    links:
    - rabbitmq
    - wise2build-biz:workflow
    - database:mysql-server
    - consul-server:eureka-server
    command:
    - --spring.datasource.url=jdbc:mysql://database:3306/scheduledb?useUnicode=true&characterEncoding=utf-8
    - --spring.datasource.password=wise2c2017
    - --spring.datasource.username=root
    - --spring.cloud.consul.host=consul-server:8500
    - --spring.rabbitmq.addresses=rabbitmq:5672
    - --spring.rabbitmq.adminAddresses=http://rabbitmq:15672
    - --spring.rabbitmq.nodes=rabbit@rabbitmq
  redis:
    image: redis
    ports:
     - "6379:6379"